#page title
page_title                                : Accquainted

# App Info
ios_app_id                                :                                          # leave blank until on App Store
ios_app_country                           : us

appstore_link                             :                                          # add when ready
playstore_link                            :                                          # add when ready
presskit_download_link                    : https://accquainted.com                  # replace with a direct file if needed

app_icon                                  : assets/appicon.png
app_name                                  : Accquainted
app_price                                 : Free
app_description                           : Campus social and dating for UCI ACC. Meet through shared culture, clubs, and events.

enable_smart_app_banner                   : true



# Information About Yourself
your_name                                 : Accquainted Team
your_link                                 : https://accquainted.com
your_city                                 : Irvine
email_address                             : contact@accquainted.com
linkedin_username                         :
linkedin_company                          :
facebook_username                         :
instagram_username                        :
twitter_username                          :
github_username                           :
youtube_username                          :
mastodon_link                             :



# Feature List
features                                  :

  - title                                 : Campus first
    description                           : Connect with UCI ACC students by clubs culture and classes
    fontawesome_icon_name                 : university

  - title                                 : UCI email verification
    description                           : Keep the community authentic with edu signup
    fontawesome_icon_name                 : envelope

  - title                                 : Simple matches and chat
    description                           : Mutual likes create a chat so you can talk right away
    fontawesome_icon_name                 : comments

  - title                                 : Events and clubs
    description                           : See mixers meetups and highlights from ACC orgs
    fontawesome_icon_name                 : calendar

  - title                                 : Privacy and safety
    description                           : Easy report and block controls plus clear data options
    fontawesome_icon_name                 : shield-alt

  - title                                 : Built for mobile
    description                           : React Native and Expo with a fast modern experience
    fontawesome_icon_name                 : mobile



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png
cover_overlay_color                       : "#0a0a0a"
cover_overlay_transparency                : 0.8

device_color                              : black

body_background_color                     : "#ffffff"

link_color                                : "#0064a4"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#0064a4"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"





####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
